INSERT INTO TB_WORKER (NAME, DAILY_IN_COME) VALUES ('Bob', 200.0);
INSERT INTO TB_WORKER (NAME, DAILY_IN_COME) VALUES ('Maria', 300.0);
INSERT INTO TB_WORKER (NAME, DAILY_IN_COME) VALUES ('Alex', 250.0);